# Generated by Django 5.0 on 2024-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_created_at_profile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerscount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
