# Generated by Django 5.0 on 2024-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_followerscount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
