# Generated by Django 5.0 on 2024-02-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='reation_type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
