# Generated by Django 5.0 on 2024-01-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
