# Generated by Django 5.0 on 2024-01-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
