# Generated by Django 5.0 on 2024-01-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciepient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
