# Generated by Django 5.0 on 2024-01-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
