# Generated by Django 5.0 on 2024-01-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
